### PR TITLE
modify terraform for enable_private_dns; refactor master to control-plane and worker to compute

### PR DESCRIPTION
**Pull request by davidfoster0127**
### Description
I've modified the terraform to properly create resources when the enable_private_dns option is selected. The primary difference is that the external LB (which I've renamed to api_apps) is created in the private subnet, and the CCM output is modified to point the CCM/CSI at the correct subnet and security list when enable_private_dns is chosen.

The majority of other changes to the file itself is a refactoring of the 2 load balancer names from external_lb and internal_lb to api_apps_lb and api_int_lb since both LBs are used whether the enable_private_dns option is selected or not.

I also refactored terraform.tf and the README.md to change "master" to "control-plane" and "worker" to "compute" to match documentation where "control-plane" and "compute" are referenced over "master" and "worker".

### Motivation
The enable_private_dns change is necessary because when we did our infrastructure.tf modifications based on OPCT testing, we did not properly account for the enable_private_dns_option. This change is necessary to give customers the option to create their cluster without being able to access it from the open internet. I left the public subnet and routes to be created in both options to give customers the ability to easily create their own VM within it.

### Testing
Ran pre-commit before committing to format and validate infrastructure.tf

I created 2 clusters with enable_private_dns set to true and false. enable_private_dns=false gave me our standard cluster setup while enable_private_dns=true was built with the api_apps LB in the private subnet. Both clusters were created successfully and I verified access to both. I was able to create a proxyVM in the public subnet of the cluster where enable_private_dns=true, copy the kubectl to the proxyVM, and view/manage the cluster. I wasn't 100% able to view the OpenShift dashboard after fiddling with my /etc/hosts file and port-forwarding 8080 -> 443 to the private IP of the api_apps LB, but I got close, getting some 401/403s for some of the responses, but it was there.

### CODE REVIEW

**Comment by makentenza** [comment]
@davidfoster0127 I'm testing this now but I do have a quick comment in the meantime

>enable_private_dns=true gave me our standard cluster setup while enable_private_dns=false was built with the api_apps LB in the private subnet

Is this a typo? It should be the other way around.

**Comment by makentenza** [comment]
@davidfoster0127 just tested private cluster deployment with no issues

`$ kubectl config view | grep server
    server: https://api.ocimak.local.fake:6443`

$ kubectl get co
NAME                                       VERSION   AVAILABLE   PROGRESSING   DEGRADED   SINCE   MESSAGE
authentication                             4.15.9    True        False         False      6m19s
baremetal                                  4.15.9    True        False         False      29m
cloud-controller-manager                   4.15.9    True        False         False      31m
cloud-credential                           4.15.9    True        False         False      33m
cluster-autoscaler                         4.15.9    True        False         False      29m
config-operator                            4.15.9    True        False         False      30m
console                                    4.15.9    True        False         False      12m
control-plane-machine-set                  4.15.9    True        False         False      29m
csi-snapshot-controller                    4.15.9    True        False         False      30m
dns                                        4.15.9    True        False         False      29m
etcd                                       4.15.9    True        False         False      28m
image-registry                             4.15.9    True        False         False      17m
ingress                                    4.15.9    True        False         False      17m
insights                                   4.15.9    True        False         False      23m
kube-apiserver                             4.15.9    True        False         False      8m38s
kube-controller-manager                    4.15.9    True        False         False      27m
kube-scheduler                             4.15.9    True        False         False      26m
kube-storage-version-migrator              4.15.9    True        False         False      30m
machine-api                                4.15.9    True        False         False      29m
machine-approver                           4.15.9    True        False         False      30m
machine-config                             4.15.9    True        False         False      28m
marketplace                                4.15.9    True        False         False      29m
monitoring                                 4.15.9    True        False         False      16m
network                                    4.15.9    True        False         False      30m
node-tuning                                4.15.9    True        False         False      17m
openshift-apiserver                        4.15.9    True        False         False      24m
openshift-controller-manager               4.15.9    True        False         False      13m
openshift-samples                          4.15.9    True        False         False      23m
operator-lifecycle-manager                 4.15.9    True        False         False      29m
operator-lifecycle-manager-catalog         4.15.9    True        False         False      29m
operator-lifecycle-manager-packageserver   4.15.9    True        False         False      24m
service-ca                                 4.15.9    True        False         False      30m
storage                                    4.15.9    True        False         False      30m

$ kubectl get nodes
NAME                                                        STATUS   ROLES                  AGE   VERSION
ocimak-compute-1.private.openshiftvcn.oraclevcn.com         Ready    worker                 23m   v1.28.7+f1b5f6c
ocimak-compute-2.private.openshiftvcn.oraclevcn.com         Ready    worker                 23m   v1.28.7+f1b5f6c
ocimak-compute-3.private.openshiftvcn.oraclevcn.com         Ready    worker                 24m   v1.28.7+f1b5f6c
ocimak-control-plane-1.private.openshiftvcn.oraclevcn.com   Ready    control-plane,master   33m   v1.28.7+f1b5f6c
ocimak-control-plane-2.private.openshiftvcn.oraclevcn.com   Ready    control-plane,master   33m   v1.28.7+f1b5f6c
ocimak-control-plane-3.private.openshiftvcn.oraclevcn.com   Ready    control-plane,master   20m   v1.28.7+f1b5f6c

**Comment by makentenza** [comment]
LGTM

**Comment by davidfoster0127** [comment]
> @davidfoster0127 I'm testing this now but I do have a quick comment in the meantime
> 
> > enable_private_dns=true gave me our standard cluster setup while enable_private_dns=false was built with the api_apps LB in the private subnet
> 
> Is this a typo? It should be the other way around.

Yes, it's a typo

**Review by nikhisin3001 — APPROVED** [review]

**Pull request merged**
